theme: minima
title: La casa de Tango
author: João Rocha
email: joaorochadesigner@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Olha só o que eu inventei agora no github pages

# social links
twitter_username: AvalancheJohn # DO NOT include the @ character, or else the build will fail!
github_username:  JoaoLNSRocha # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
